# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Articulo', models.CharField(max_length=100)),
                ('Tipo', models.CharField(max_length=10)),
                ('Prestado', models.BooleanField(default=False)),
                ('Ultimo_presto', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=200)),
                ('Autor', models.CharField(max_length=150)),
                ('Edicion', models.CharField(max_length=20)),
                ('Publicacion', models.CharField(max_length=40)),
                ('Editorial', models.CharField(max_length=50)),
                ('Ano', models.CharField(max_length=4)),
                ('Paginas', models.IntegerField()),
                ('Volumen', models.CharField(max_length=10)),
                ('Cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
                ('E_mail', models.EmailField(max_length=254)),
                ('Celular', models.CharField(max_length=10)),
                ('Nivel_academico', models.IntegerField(choices=[(1, b'Primaria'), (2, b'Secundaria'), (3, b'Preparatoria'), (4, b'Universidad')], default=1)),
                ('Escuela', models.CharField(blank=True, max_length=50, null=True)),
                ('Capacitacion', models.CharField(blank=True, max_length=50, null=True)),
                ('Matricula', models.CharField(blank=True, max_length=30, null=True)),
                ('Semestre', models.CharField(blank=True, max_length=50, null=True)),
                ('Programa', models.IntegerField(choices=[(1, b'Voluntariado'), (2, b'Servicio Social 1era Etapa'), (3, b'Servicio Social 2da Etapa'), (4, b'Practicas Profesionales'), (5, b'Proyecto de Vinculacion')], default=1)),
                ('Horas_realizar', models.IntegerField()),
                ('Horas_hechas', models.IntegerField()),
                ('Turno', models.IntegerField(choices=[(1, b'Matutino'), (2, b'Vespertino'), (3, b'Mixto')], default=1)),
                ('Fecha_inicio', models.DateField()),
                ('Seguro', models.BooleanField(default=False)),
                ('Contacto_emergencia', models.TextField(blank=True, max_length=200, null=True)),
                ('Informacion', models.BooleanField(default=True)),
            ],
        ),
    ]
