# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-27 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfea_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voluntario',
            name='Nivel_academico',
            field=models.IntegerField(choices=[(1, 'Primaria'), (2, 'Secundaria'), (3, 'Preparatoria'), (4, 'Universidad')], default=1),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='Programa',
            field=models.IntegerField(choices=[(1, 'Voluntariado'), (2, 'Servicio Social 1era Etapa'), (3, 'Servicio Social 2da Etapa'), (4, 'Practicas Profesionales'), (5, 'Proyecto de Vinculacion')], default=1),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='Turno',
            field=models.IntegerField(choices=[(1, 'Matutino'), (2, 'Vespertino'), (3, 'Mixto')], default=1),
        ),
        migrations.AlterModelTable(
            name='herramienta',
            table='herramienta',
        ),
        migrations.AlterModelTable(
            name='libro',
            table='libro',
        ),
        migrations.AlterModelTable(
            name='voluntario',
            table='voluntario',
        ),
    ]
