# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-14 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfea_app', '0002_auto_20161027_0057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herramienta',
            name='Articulo',
        ),
        migrations.RemoveField(
            model_name='herramienta',
            name='Prestado',
        ),
        migrations.RemoveField(
            model_name='herramienta',
            name='Tipo',
        ),
        migrations.RemoveField(
            model_name='herramienta',
            name='Ultimo_presto',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='Paginas',
        ),
        migrations.AddField(
            model_name='herramienta',
            name='Cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='herramienta',
            name='Codigo',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='herramienta',
            name='Concepto',
            field=models.CharField(default='herramienta', max_length=50),
        ),
        migrations.AddField(
            model_name='herramienta',
            name='Descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herramienta',
            name='Marca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='herramienta',
            name='Modelo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='herramienta',
            name='Numero_Serie',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='Volumen',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
