# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-17 02:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pfea_app', '0003_auto_20161114_0251'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasuraRecogida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Zona', models.CharField(max_length=50)),
                ('Adultos', models.IntegerField()),
                ('Ninos', models.IntegerField(verbose_name='Niños')),
                ('Colillas', models.IntegerField()),
                ('Envoltorios', models.IntegerField()),
                ('Envases_para_llevar_plastico', models.IntegerField()),
                ('Envases_para_llevar_unicel', models.IntegerField()),
                ('Taparroscas', models.IntegerField()),
                ('Corcholatas', models.IntegerField()),
                ('Tapas', models.IntegerField()),
                ('Popotes', models.IntegerField()),
                ('Cubiertos', models.IntegerField()),
                ('Botellas_plastico', models.IntegerField()),
                ('Botellas_vidrio', models.IntegerField()),
                ('Latas', models.IntegerField()),
                ('Bolsas_comestibles_plastico', models.IntegerField()),
                ('Bolsas_plastico', models.IntegerField()),
                ('Bolsas_papel', models.IntegerField()),
                ('Vasos_platos_papel', models.IntegerField()),
                ('Vasos_platos_plastico', models.IntegerField()),
                ('Vasos_platos_unicel', models.IntegerField()),
                ('Boyas_trampas', models.IntegerField()),
                ('Redes_pesca', models.IntegerField()),
                ('Cuerda', models.IntegerField()),
                ('Linea_pesca', models.IntegerField()),
                ('Contenedores_6_latas', models.IntegerField()),
                ('Otros_plastico_unicel', models.IntegerField()),
                ('Otras_botellas_plastico', models.IntegerField()),
                ('Cintas_embalar', models.IntegerField()),
                ('Envoltorio_tabaco', models.IntegerField()),
                ('Electrodomesticos', models.IntegerField()),
                ('Globos', models.IntegerField()),
                ('Puntas_puros', models.IntegerField()),
                ('Encendedores', models.IntegerField()),
                ('Materiales_construccion', models.IntegerField()),
                ('Cohetes', models.IntegerField()),
                ('Llantas', models.IntegerField()),
                ('Condones', models.IntegerField()),
                ('Pañales', models.IntegerField()),
                ('Jeringas', models.IntegerField()),
                ('Tampones', models.IntegerField()),
                ('Ropa', models.IntegerField()),
                ('Guantes_latex', models.IntegerField()),
                ('Pedazos_unicel', models.IntegerField()),
                ('Pedazos_vidrio', models.IntegerField()),
                ('Pedazos_plastico', models.IntegerField()),
                ('Pedazos_papel', models.IntegerField()),
                ('Animales_muertos', models.IntegerField()),
                ('Animales_lesionados', models.IntegerField()),
                ('Animales_enredados', models.IntegerField()),
                ('Animales_notas', models.TextField()),
                ('Objetos_preocupacion_local', models.TextField()),
                ('Costales_basura', models.IntegerField()),
                ('Peso_costales', models.IntegerField()),
                ('Distancia_limpiada', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InventarioDeHerramientas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Responsable1', models.CharField(blank=True, max_length=200, null=True)),
                ('Fecha', models.DateField()),
                ('Hora', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudDeVoluntario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
                ('E_mail', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('Celular', models.CharField(max_length=10)),
                ('Nivel_academico', models.IntegerField(choices=[(1, 'Primaria'), (2, 'Secundaria'), (3, 'Preparatoria'), (4, 'Universidad')], default=1, verbose_name='Nivel académico')),
                ('Escuela', models.CharField(blank=True, max_length=50, null=True)),
                ('Capacitacion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Capacitación')),
                ('Matricula', models.CharField(blank=True, max_length=30, null=True)),
                ('Semestre', models.CharField(blank=True, max_length=50, null=True)),
                ('Programa', models.IntegerField(choices=[(1, 'Voluntariado'), (2, 'Servicio Social 1era Etapa'), (3, 'Servicio Social 2da Etapa'), (4, 'Practicas Profesionales'), (5, 'Proyecto de Vinculacion')], default=1)),
                ('Horas_realizar', models.IntegerField(verbose_name='Horas a realizar')),
                ('Turno', models.IntegerField(choices=[(1, 'Matutino'), (2, 'Vespertino'), (3, 'Mixto')], default=1)),
                ('Fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('Seguro', models.BooleanField(default=False)),
                ('Contacto_emergencia', models.TextField(blank=True, max_length=200, null=True)),
                ('Informacion', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='Codigo',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='Modelo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='Numero_Serie',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de serie'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='Cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='Capacitacion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Capacitación'),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='E_mail',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='Fecha_inicio',
            field=models.DateField(verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='Horas_realizar',
            field=models.IntegerField(verbose_name='Horas a realizar'),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='Nivel_academico',
            field=models.IntegerField(choices=[(1, 'Primaria'), (2, 'Secundaria'), (3, 'Preparatoria'), (4, 'Universidad')], default=1, verbose_name='Nivel académico'),
        ),
        migrations.AlterModelTable(
            name='herramienta',
            table=None,
        ),
        migrations.AlterModelTable(
            name='libro',
            table=None,
        ),
        migrations.AlterModelTable(
            name='voluntario',
            table=None,
        ),
        migrations.AddField(
            model_name='herramienta',
            name='Inventario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pfea_app.InventarioDeHerramientas'),
            preserve_default=False,
        ),
    ]
