# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-01 06:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfea_app', '0006_auto_20161130_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herramienta',
            name='Inventario',
        ),
        migrations.DeleteModel(
            name='InventarioDeHerramientas',
        ),
    ]
