# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-02 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfea_app', '0007_auto_20161201_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='Editorial',
            field=models.CharField(max_length=100),
        ),
    ]
